FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    build-essential \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* # Clean up apt cache to reduce image size
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
# CMD ["python3", "-m", "vllm.entrypoints.openai.api_server", "--host", "0.0.0.0", "--port", "8000", "--max-model-len", "32768", "--enforce-eager", "--gpu-memory-utilization=1.0", "--dtype", "float16", "--max-num-seqs", "1", "--model", "/app/models/Ministral-8B-Instruct-2410-awq"]
CMD ["python3", "-m", "vllm.entrypoints.openai.api_server", "--host", "0.0.0.0", "--port", "8000", "--max-model-len", "32768", "--enforce-eager", "--gpu-memory-utilization=1.0", "--dtype", "float16", "--max-num-seqs", "1", "--model", "/app/models/Skywork-o1-Open-Llama-3.1-8B-awq"]
